FROM python:3.6.5-slim-jessie AS builder-image

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
                    libmysqlclient-dev \
                    build-essential \
                    python3-dev \
                    python2.7-dev \
                    libldap2-dev \
                    libsasl2-dev \
                    slapd \
                    ldap-utils \
                    python-tox \
                    lcov \
                    valgrind\
                    curl\
                    python-dev \
                    gcc \
                    musl-dev \
                    libffi-dev \
                    ca-certificates \
                    git\
                    bash


# create and activate virtual environment
# using final folder name to avoid path issues with packages
RUN python3 -m venv /home/cabot/venv
ENV PATH="/home/cabot/venv/bin:$PATH"


ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

RUN mkdir /code

WORKDIR /code

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

########################################################
FROM python:3.6.5-slim-jessie AS runner-image

RUN apt-get update && apt-get install  --no-install-recommends -y python3-venv && \
apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd --create-home cabot
COPY --from=builder-image /home/cabot/venv /home/cabot/venv

USER cabot
RUN mkdir /home/cabot/code
WORKDIR /home/cabot/code
COPY . .

EXPOSE 8000

# make sure all messages always reach console
ENV PYTHONUNBUFFERED=1

# activate virtual environment
ENV VIRTUAL_ENV=/home/cabot/venv
ENV PATH="/home/cabot/venv/bin:$PATH"

# /dev/shm is mapped to shared memory and should be used for gunicorn heartbeat
# this will improve performance and avoid random freezes
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]


#ENTRYPOINT ["./docker-entrypoint.sh"]