# Constant definitions

from cabot.metricsapp.defs import GRAFANA_SYNC_TIMEDELTA_MINUTES

MINUTE_IN_SECONDS = 60

RUN_ALL_CHECKS_FREQUENCY = MINUTE_IN_SECONDS  # 1 minute
UPDATE_SHIFTS_FREQUENCY = 30 * MINUTE_IN_SECONDS  # 30 minutes
CLEAN_DB_FREQUENCY = 24 * 60 * MINUTE_IN_SECONDS  # full day
SYNC_ALL_GRAFANA_CHECKS_FREQUENCY = GRAFANA_SYNC_TIMEDELTA_MINUTES * MINUTE_IN_SECONDS
UPDATE_SERVICE_FREQUENCY = 30
