# Generated by Django 3.2.5 on 2021-08-07 15:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=30, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_cabotapp.alertplugin_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('alerts_enabled', models.BooleanField(default=True, help_text='Alert when this service is not healthy.')),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('email_alert', models.BooleanField(default=False)),
                ('hipchat_alert', models.BooleanField(default=True)),
                ('sms_alert', models.BooleanField(default=False)),
                ('telephone_alert', models.BooleanField(default=False, help_text='Must be enabled, and check importance set to Critical, to receive telephone alerts.')),
                ('overall_status', models.TextField(default='PASSING')),
                ('old_overall_status', models.TextField(default='PASSING')),
                ('hackpad_id', models.TextField(blank=True, help_text='Gist, Hackpad or Refheap js embed with recovery instructions e.g. https://you.hackpad.com/some_document.js', null=True, verbose_name='Embedded recovery instructions')),
                ('runbook_link', models.TextField(blank=True, help_text='Link to the service runbook on your wiki.')),
                ('address', models.TextField(blank=True, help_text='Address (IP/Hostname) of service.')),
                ('alerts', models.ManyToManyField(blank=True, help_text='Alerts channels through which you wish to be notified', to='cabotapp.AlertPlugin')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('alerts_enabled', models.BooleanField(default=True, help_text='Alert when this service is not healthy.')),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('email_alert', models.BooleanField(default=False)),
                ('hipchat_alert', models.BooleanField(default=True)),
                ('sms_alert', models.BooleanField(default=False)),
                ('telephone_alert', models.BooleanField(default=False, help_text='Must be enabled, and check importance set to Critical, to receive telephone alerts.')),
                ('overall_status', models.TextField(default='PASSING')),
                ('old_overall_status', models.TextField(default='PASSING')),
                ('hackpad_id', models.TextField(blank=True, help_text='Gist, Hackpad or Refheap js embed with recovery instructions e.g. https://you.hackpad.com/some_document.js', null=True, verbose_name='Embedded recovery instructions')),
                ('runbook_link', models.TextField(blank=True, help_text='Link to the service runbook on your wiki.')),
                ('url', models.TextField(blank=True, help_text='URL of service.')),
                ('is_public', models.BooleanField(default=False, help_text='The service will be shown in the public home', verbose_name='Is Public')),
                ('alerts', models.ManyToManyField(blank=True, help_text='Alerts channels through which you wish to be notified', to='cabotapp.AlertPlugin')),
                ('instances', models.ManyToManyField(blank=True, help_text='Instances this service is running on.', to='cabotapp.Instance')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StatusCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField(default=True, help_text='If not active, check will not be used to calculate service status and will not trigger alerts.')),
                ('importance', models.CharField(choices=[('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='ERROR', help_text='Severity level of a failure. Critical alerts are for failures you want to wake you up at 2am, Errors are things you can sleep through but need to fix in the morning, and warnings for less important things.', max_length=30)),
                ('frequency', models.IntegerField(default=5, help_text='Minutes between each check.')),
                ('debounce', models.IntegerField(default=0, help_text='Number of successive failures permitted before check will be marked as failed. Default is 0, i.e. fail on first failure.', null=True)),
                ('calculated_status', models.CharField(blank=True, choices=[('passing', 'passing'), ('intermittent', 'intermittent'), ('failing', 'failing')], default='passing', max_length=50)),
                ('last_run', models.DateTimeField(null=True)),
                ('cached_health', models.TextField(editable=False, null=True)),
                ('metric', models.TextField(help_text='fully.qualified.name of the Graphite metric you want to watch. This can be any valid Graphite expression, including wildcards, multiple hosts, etc.', null=True)),
                ('check_type', models.CharField(choices=[('>', 'Greater than'), ('>=', 'Greater than or equal'), ('<', 'Less than'), ('<=', 'Less than or equal'), ('==', 'Equal to')], max_length=100, null=True)),
                ('value', models.TextField(help_text='If this expression evaluates to true, the check will fail (possibly triggering an alert).', null=True)),
                ('expected_num_hosts', models.IntegerField(default=0, help_text='The minimum number of data series (hosts) you expect to see.', null=True)),
                ('allowed_num_failures', models.IntegerField(default=0, help_text='The maximum number of data series (metrics) you expect to fail. For example, you might be OK with 2 out of 3 webservers having OK load (1 failing), but not 1 out of 3 (2 failing).', null=True)),
                ('endpoint', models.TextField(help_text='HTTP(S) endpoint to poll.', null=True, validators=[django.core.validators.URLValidator()])),
                ('username', models.TextField(blank=True, help_text='Basic auth username.', null=True)),
                ('password', models.TextField(blank=True, help_text='Basic auth password.', null=True)),
                ('text_match', models.TextField(blank=True, help_text='Regex to match against source of page.', null=True)),
                ('status_code', models.TextField(default=200, help_text='Status code expected from endpoint.', null=True)),
                ('timeout', models.IntegerField(default=30, help_text='Time out after this many seconds.', null=True)),
                ('verify_ssl_certificate', models.BooleanField(default=True, help_text='Set to false to allow not try to verify ssl certificates (default True)')),
                ('max_queued_build_time', models.IntegerField(blank=True, help_text='Alert if build queued for more than this many minutes.', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_cabotapp.statuscheck_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, default='', max_length=20)),
                ('hipchat_alias', models.CharField(blank=True, default='', max_length=50)),
                ('fallback_alert_user', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('uid', models.TextField()),
                ('last_modified', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatusSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('num_checks_active', models.IntegerField(default=0)),
                ('num_checks_passing', models.IntegerField(default=0)),
                ('num_checks_failing', models.IntegerField(default=0)),
                ('overall_status', models.TextField(default='PASSING')),
                ('did_send_alert', models.IntegerField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='cabotapp.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='service',
            name='status_checks',
            field=models.ManyToManyField(blank=True, help_text='Checks used to calculate service status.', to='cabotapp.StatusCheck'),
        ),
        migrations.AddField(
            model_name='service',
            name='users_to_notify',
            field=models.ManyToManyField(blank=True, help_text='Users who should receive alerts.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InstanceStatusSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('num_checks_active', models.IntegerField(default=0)),
                ('num_checks_passing', models.IntegerField(default=0)),
                ('num_checks_failing', models.IntegerField(default=0)),
                ('overall_status', models.TextField(default='PASSING')),
                ('did_send_alert', models.IntegerField(default=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='cabotapp.instance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='instance',
            name='status_checks',
            field=models.ManyToManyField(blank=True, help_text='Checks used to calculate service status.', to='cabotapp.StatusCheck'),
        ),
        migrations.AddField(
            model_name='instance',
            name='users_to_notify',
            field=models.ManyToManyField(blank=True, help_text='Users who should receive alerts.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AlertAcknowledgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('cancelled_time', models.DateTimeField(blank=True, null=True)),
                ('cancelled_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelleduser_set', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabotapp.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCheckResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('time_complete', models.DateTimeField(db_index=True, null=True)),
                ('raw_data', models.TextField(null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('error', models.TextField(null=True)),
                ('job_number', models.PositiveIntegerField(null=True)),
                ('consecutive_failures', models.PositiveIntegerField(null=True)),
                ('status_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabotapp.statuscheck')),
            ],
            options={
                'ordering': ['-time_complete'],
                'index_together': {('status_check', 'id'), ('status_check', 'time_complete')},
            },
        ),
        migrations.CreateModel(
            name='AlertPluginUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=30)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_cabotapp.alertpluginuserdata_set+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cabotapp.userprofile')),
            ],
            options={
                'unique_together': {('title', 'user')},
            },
        ),
    ]
