# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabotapp', '0001_initial'),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscheck',
            name='check_plugin',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='status_check', to='plugins.StatusCheckPluginModel'),
        ),
        migrations.AddField(
            model_name='statuscheck',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicestatussnapshot',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='cabotapp.Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='alerts',
            field=models.ManyToManyField(blank=True, help_text=b'Alerts channels through which you wish to be notified', to='plugins.AlertPluginModel'),
        ),
        migrations.AddField(
            model_name='service',
            name='instances',
            field=models.ManyToManyField(blank=True, help_text=b'Instances this service is running on.', to='cabotapp.Instance'),
        ),
        migrations.AddField(
            model_name='service',
            name='status_checks',
            field=models.ManyToManyField(blank=True, help_text=b'Checks used to calculate service status.', to='cabotapp.StatusCheck'),
        ),
        migrations.AddField(
            model_name='service',
            name='users_to_notify',
            field=models.ManyToManyField(blank=True, help_text=b'Users who should receive alerts.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instancestatussnapshot',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='cabotapp.Instance'),
        ),
        migrations.AddField(
            model_name='instance',
            name='alerts',
            field=models.ManyToManyField(blank=True, help_text=b'Alerts channels through which you wish to be notified', to='plugins.AlertPluginModel'),
        ),
        migrations.AddField(
            model_name='instance',
            name='status_checks',
            field=models.ManyToManyField(blank=True, help_text=b'Checks used to calculate service status.', to='cabotapp.StatusCheck'),
        ),
        migrations.AddField(
            model_name='instance',
            name='users_to_notify',
            field=models.ManyToManyField(blank=True, help_text=b'Users who should receive alerts.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertpluginuserdata',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_cabotapp.alertpluginuserdata_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='alertpluginuserdata',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cabotapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='alertplugin',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_cabotapp.alertplugin_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='alertacknowledgement',
            name='cancelled_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelleduser_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertacknowledgement',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabotapp.Service'),
        ),
        migrations.AddField(
            model_name='alertacknowledgement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='statuscheckvariable',
            unique_together=set([('status_check', 'key')]),
        ),
        migrations.AlterIndexTogether(
            name='statuscheckresult',
            index_together=set([('status_check', 'time_complete')]),
        ),
        migrations.AlterUniqueTogether(
            name='alertpluginuserdata',
            unique_together=set([('title', 'user')]),
        ),
    ]
