# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-09 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
        ('cabotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCheckVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', picklefield.fields.PickledObjectField(editable=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='statuscheck',
            name='check_plugin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_check', to='plugins.StatusCheckPluginModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instance',
            name='alerts',
            field=models.ManyToManyField(blank=True, help_text=b'Alerts channels through which you wish to be notified', to='plugins.AlertPluginModel'),
        ),
        migrations.AddField(
            model_name='service',
            name='alert_plugin_models',
            field=models.ManyToManyField(blank=True, help_text=b'Alerts channels through which you wish to be notified', to='plugins.AlertPluginModel'),
        ),
        migrations.AddField(
            model_name='statuscheckvariable',
            name='status_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabotapp.StatusCheck'),
        ),
        migrations.RenameField(
            model_name='statuscheckresult',
            old_name='check',
            new_name='status_check',
        ),
        migrations.AlterUniqueTogether(
            name='statuscheckvariable',
            unique_together=set([('status_check', 'key')]),
        ),
    ]
