# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-09 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0003_plugins_data_migrations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphiteStatusCheck',
        ),
        migrations.DeleteModel(
            name='HttpStatusCheck',
        ),
        migrations.DeleteModel(
            name='ICMPStatusCheck',
        ),
        migrations.DeleteModel(
            name='JenkinsStatusCheck',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='email_alert',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='hipchat_alert',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='sms_alert',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='telephone_alert',
        ),
        migrations.RemoveField(
            model_name='service',
            name='alerts',
        ),
        migrations.RemoveField(
            model_name='service',
            name='email_alert',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hipchat_alert',
        ),
        migrations.RemoveField(
            model_name='service',
            name='sms_alert',
        ),
        migrations.RemoveField(
            model_name='service',
            name='telephone_alert',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='allowed_num_failures',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='check_type',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='expected_num_hosts',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='max_queued_build_time',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='password',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='text_match',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='timeout',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='username',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='value',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='verify_ssl_certificate',
        ),
    ]
