# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0004_remove_old_plugins_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='alert_plugin_models',
            new_name='alerts',
        ),
    ]
