# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-29 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0007_statuscheckresult_consecutive_failures'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscheck',
            name='bearer_endpoint',
            field=models.TextField(blank=True, help_text=b'Bearer Authentication endpoint', null=True),
        ),
        migrations.AddField(
            model_name='statuscheck',
            name='bearer_request_body',
            field=models.TextField(blank=True, help_text=b'Bearer Authentication request body', null=True),
        ),
    ]
