# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-11 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0007_statuscheckresult_consecutive_failures'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscheck',
            name='follow_redirects',
            field=models.BooleanField(default=True, help_text=b'Uncheck to prevent Cabot from following HTTP redirections (default True)'),
        ),
    ]
