# Generated by Django 3.2.5 on 2021-07-20 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0008_auto_20210707_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Service',
            name='status_checks',
            field=models.ManyToManyField(blank=True, help_text='Checks used to calculate service status.', to='cabotapp.StatusCheck'),
        ),
        migrations.AlterField(
            model_name='Instance',
            name='status_checks',
            field=models.ManyToManyField(blank=True, help_text='Checks used to calculate service status.', to='cabotapp.StatusCheck'),
        ),
        migrations.AlterField(
            model_name='StatusCheckResult',
            name='status_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabotapp.statuscheck'),
        ),
    ]
