# Generated by Django 3.2.5 on 2021-07-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0009_auto_20210719_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenkinsstatuscheck',
            name='jenkins_config',
        ),
        migrations.RemoveField(
            model_name='jenkinsstatuscheck',
            name='statuscheck_ptr',
        ),
        migrations.DeleteModel(
            name='GraphiteStatusCheck',
        ),
        migrations.DeleteModel(
            name='ICMPStatusCheck',
        ),
        migrations.DeleteModel(
            name='JenkinsConfig',
        ),
        migrations.DeleteModel(
            name='JenkinsStatusCheck',
        ),
    ]
