version: '3'
services:
  db:
    container_name: cabot_pg
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - datavolume:/var/lib/postgresql/data

  pgadmin:
    container_name: cabot_pg_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  redis:
    container_name: cabot_redis
    image: redislabs/redismod
    restart: always
    ports:
      - 6379:6379

  redisinsight:
    container_name: cabot_redis_admin
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - '8001:8001'

  web:
    build: .
    extends:
      file: docker-compose-base.yml
      service: base
    env_file:
      - conf/development.env
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - redis
      - db

  worker-beat:
    extends:
      file: docker-compose-base.yml
      service: base
    env_file:
      - conf/development.env
    command: celery -A cabot worker --beat --scheduler django --loglevel=info
    environment:
      - SKIP_INIT=1
      - WAIT_FOR_MIGRATIONS=1
    links:
      - redis
      - db
   

volumes:
  datavolume:

